on:
    push:
      branches:
        - '*'         # matches every branch that doesn't contain a '/'
        - '*/*'       # matches every branch containing a single '/'
        - '**'        # matches every branch
      paths-ignore:
        - README.md
        - README.es.md
    pull_request:
      branches:
        - main
        - master
        - develop
        - experimental
        - test/**
        - bugfix/**
        - feature/**
      paths-ignore:
        - README.md
        - README.es.md
        - docker/*

jobs:
    install-and-build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - uses: pnpm/action-setup@v4
          name: Install pnpm
  
        - name: Install Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 18
            cache: 'pnpm'
  
        - name: Install dependencies
          run: pnpm install
        
        - name: Build Project
          run: pnpm nuxt build